version: "3.9"

services:
  full-monty-website:
    build:
      args:
        NEXTJS_PORT: ${NEXTJS_PORT}
      context: ./website
      dockerfile: Dockerfile
    container_name: full-monty-website
    entrypoint: ["npm", "run", "${START_SCRIPT}"]
    env_file: website/.env.local
    expose:
      - ${NEXTJS_PORT}:${NEXTJS_PORT}
    networks:
      - full_monty_nw
    ports:
      - ${NEXTJS_PORT}:${NEXTJS_PORT}
    restart: on-failure
    volumes:
      - type: bind
        source: website/src
        target: /var/www/html/src

  full-monty-api:
    build:
      args:
        NODE_PORT: ${NODE_PORT}
      context: ./api
      dockerfile: Dockerfile
    container_name: full-monty-api
    entrypoint: ["npm", "run", "${START_SCRIPT}"]
    env_file: api/.env
    expose:
      - ${NODE_PORT}:${NODE_PORT}
    networks:
      - full_monty_nw
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    restart: on-failure
    volumes:
      - type: bind
        source: api/src
        target: /var/www/html/src
      - type: bind
        source: api/database.sqlite
        target: /var/www/html/database.sqlite

networks:
  full_monty_nw:
    driver: bridge
