version: "3.9"

services:
  webserver:
    build:
      context: ../
      dockerfile: .docker/webserver/Dockerfile
    command: npm run dev
    container_name: webserver
    depends_on:
      - mongo
    env_file:
      - ../.env.production
    expose:
      - "9090:9090"
    networks:
      - full_monty_nw
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - type: bind
        source: ../
        target: /var/www/html

  mongo:
    container_name: mongo
    env_file:
      - ../.env.production
    image: mongo:5.0-focal
    networks:
      - full_monty_nw
    restart: always

networks:
  full_monty_nw:
    driver: bridge
