version: "3.9"

services:
  webserver:
    build:
      context: ../
      dockerfile: .docker/webserver/Dockerfile
    command: npm run dev
    container_name: webserver
    depends_on:
      - mongo
    environment:
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      MONGO_USER: chris
      MONGO_PASSWORD: secretpassword
    expose:
      - "9090:9090"
    networks:
      - "full_monty_nw"
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - type: bind
        source: ../
        target: /var/www/html

  mongo:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: chris
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    image: mongo:5.0-focal
    networks:
      - "full_monty_nw"
    restart: always

  mongo-express:
    container_name: mongo-ui
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: chris
      ME_CONFIG_BASICAUTH_PASSWORD: secretpassword
      ME_CONFIG_MONGODB_ADMINUSERNAME: chris
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_BASEURL: /
    image: mongo-express:0.54
    networks:
      - "full_monty_nw"
    ports:
      - 8081:8081
    restart: always

networks:
  full_monty_nw:
    driver: bridge
